### ISSUE TITLE
Touchpad doesn't work on F35 using latest copr packages

### ISSUE THREAD

**Issue by cybik** [jmontleon/pixelbook-fedora#1]
As per the title. On a very fresh install of Fedora 35 in which I did only your repo's instructions, sound and backlight are working as advertised, but using the touchpad doesn't do anything.

I rebooted into a Pop_OS liveusb session and it worked fine, so there might be something odd with the kernel modules here.

**Comment by jmontleon** [comment]
Shouldn't be anything with kernel modules. I'm on Fedora 35 and the touchpad is working fine. Some additional information below that might help narrow down what could be different:

```
[jason@pixelbook ~]$ uname -a
Linux pixelbook.montleon.intra 5.14.9-301.pixelbook.fc35.x86_64 #1 SMP Thu Sep 30 19:04:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
[jason@pixelbook ~]$ cat /etc/redhat-release 
Fedora release 35 (Thirty Five)
```

Only config I have is below. It shouldn't be necessary, just tweaks some behavior:
```
rpm -q --whatprovides /etc/X11/xorg.conf.d/99-pixelbook-touchpad-tweak.conf
pixelbook-touchpad-tweak-1.0.0-1.fc35.noarch
```

Contents:
```
Section "InputClass"
        Identifier "TouchPad"
        MatchIsTouchpad "on"
        MatchDevicePath "/dev/input/event*"
        Option "Tapping" "on"
        Option "TappingDrag" "off"
        Option "TappingDragLock" "off"
        Driver "libinput"
EndSection
```

I am using 4.14 of the MrChromebox firmware:
```
$ sudo dmidecode | grep MrChromebox
	Version: MrChromebox-4.14
```

Using Xfce and the following Xorg packages:
```
xorg-x11-drv-amdgpu-21.0.0-1.fc35.x86_64
xorg-x11-drv-ati-19.1.0-6.fc35.x86_64
xorg-x11-drv-evdev-2.10.6-10.fc35.x86_64
xorg-x11-drv-fbdev-0.5.0-9.fc35.x86_64
xorg-x11-drv-intel-2.99.917-51.20200205.fc35.x86_64
xorg-x11-drv-libinput-1.2.0-1.fc35.x86_64
xorg-x11-drv-nouveau-1.0.17-2.fc35.x86_64
xorg-x11-drv-openchrome-0.6.400-2.20210215git5dbad06.fc35.x86_64
xorg-x11-drv-qxl-0.1.5-20.fc35.x86_64
xorg-x11-drv-vesa-2.4.0-12.fc35.x86_64
xorg-x11-drv-vmware-13.2.1-16.fc35.x86_64
xorg-x11-drv-wacom-0.40.0-2.fc35.x86_64
xorg-x11-drv-wacom-serial-support-0.40.0-2.fc35.x86_64
xorg-x11-fonts-ISO8859-1-100dpi-7.5-32.fc35.noarch
xorg-x11-proto-devel-2021.5-1.fc35.noarch
xorg-x11-server-common-1.20.11-2.fc35.x86_64
xorg-x11-server-Xorg-1.20.11-2.fc35.x86_64
xorg-x11-xauth-1.1-9.fc35.x86_64
xorg-x11-xinit-1.4.0-12.fc35.x86_64
```

**Comment by cybik** [comment]
Of course, after a full power down it started working. Sorry for the bother.

**Comment by jmontleon** [comment]
No problem at all, glad you got it working!

**Comment by arthurlt** [comment]
Are there any plans to get the touchpad working reliably without a hard reboot (Refresh+Power)? Anytime I restart the machine the touchpad doesn't work until the hard reboot.

**Comment by jmontleon** [comment]
I don't have any idea what causes this. Might be a question for MrChromebox. Perhaps something in firmware, or he could at least point in the direction to investigate. I definitely don't seem to experience this as much as some do, though I've definitely seen it.

**Comment by jmontleon** [comment]
I wonder if any of these might help in the situation: https://support.google.com/pixelbook/answer/9133994
```
Fix touchpad problems
If your touchpad stops working, try these steps:

Make sure there is no dust or dirt on the touchpad.
Press the Esc key several times.
Drumroll your fingers on the touchpad for ten seconds.
Pixel Slate users: Disconnect Pixel Slate from the keyboard, then reconnect.
Turn your device off, then back on again.
Perform a hard reset.
If you have more than one account on your device, delete the account that has problems with the touchpad, then re-add the account.
```

I definitely recall having this problem with ChromeOS on occasion and mashing the Esc key helping at least some of the time.

**Comment by arthurlt** [comment]
> I wonder if any of these might help in the situation: https://support.google.com/pixelbook/answer/9133994
> 
> ```
> Fix touchpad problems
> If your touchpad stops working, try these steps:
> 
> Make sure there is no dust or dirt on the touchpad.
> Press the Esc key several times.
> Drumroll your fingers on the touchpad for ten seconds.
> Pixel Slate users: Disconnect Pixel Slate from the keyboard, then reconnect.
> Turn your device off, then back on again.
> Perform a hard reset.
> If you have more than one account on your device, delete the account that has problems with the touchpad, then re-add the account.
> ```
> 
> I definitely recall having this problem with ChromeOS on occasion and mashing the Esc key helping at least some of the time.

I had never come across this page. I'll give it a shot next time I reboot. 

I wonder why your experience differs? Are you running the updated touchpad firmware that MrChromebox's can roll back?

**Comment by jmontleon** [comment]
I've never downgraded or upgraded the touchpad firmware. My understanding is/was that downgrade was only necessary for Windows, which I've never run on it.

The other night I upgraded to coreboot 4.16 and was testing that it really fixed https://github.com/jmontleon/pixelbook-fedora/issues/26. I hit it twice in a row. Before that it had been quite a long time.

It could also be that I typically turn mine on in the evening, use it for a few hours in front of the TV, then shutdown. As I think about it I don't reboot terribly often, though I do if I get a kernel update or am testing kernels, so it isn't the case that I never do.

I asked MrChromebox in case he has any ideas. The worst he can say is no. Sometimes a fresh set of eyes will see something another has been overlooking for eons. https://github.com/MrChromebox/firmware/issues/344

**Comment by arthurlt** [comment]
> I've never downgraded or upgraded the touchpad firmware. My understanding is/was that downgrade was only necessary for Windows, which I've never run on it.
> 
> The other night I upgraded to coreboot 4.16 and was testing that it really fixed #26. I hit it twice in a row. Before that it had been quite a long time.

I believe I'm running whatever the latest firmware is as I was running ChromeOS until Monday so I'm also using coreboot 4.16 and your latest kernel 5.17.

Thanks for opening that issue, I've subscribed and looking forward to hearing his input.

**Comment by jmontleon** [comment]
Spotted this while looking around. Apparently ChromeOS has flashed the touchpad firmware in the past. Perhaps my better experience is due to an older firmware. Will have to look and see how to tell what version(s) we have. 
https://www.reddit.com/r/PixelBook/comments/dtxmm9/comment/f6zebry/?utm_source=share&utm_medium=web2x&context=3

**Comment by jmontleon** [comment]
A crummy workaround, but if you want to try it:

Create:
```
$ cat /usr/lib/systemd/system/pixelbook-
pixelbook-aer.service       pixelbook-touchpad.service
[jason@pixelbook ~]$ cat /usr/lib/systemd/system/pixelbook-touchpad.service 
[Unit]
Description=Workaround for Pixelbook's touchpa

[Service]
Type=oneshot
ExecStart=rmmod i2c_hid_acpi i2c_hid
ExecStart=modprobe i2c_hid_acpi
RemainAfterExit=yes

[Install]
WantedBy=graphical.target
```

```
sudo systemctl daemon-reload 
sudo systemctl enable --now pixelbook-touchpad.service
```

Should be able to reboot all you want and not lose the mouse. If we don't get a better answer I'll package this up...

**Comment by jmontleon** [comment]
I guess I didn't link it, but it looks similar to:
https://bugzilla.redhat.com/show_bug.cgi?id=1442699

**Comment by jmontleon** [comment]
https://github.com/jmontleon/pixelbook-fedora/commit/117fa248203f570f53c44450ce8540f82c6fdcfe instroduces a workaround that should hopefully mask the issue.
