### ISSUE TITLE
quick thanks

### ISSUE THREAD

**Issue by huynle** [jmontleon/pixelbook-fedora#10]
i dont have anything to report, but just want to drop by and say thank you @jmontleon , you have made the dream i had three years ago possible. i forced my way down the debian path to build and rebuild the newer kernels, and this was it. without an hour, everything was up and running! much kudos! everything is working perfectly, development laptop and  xournalpp for notes with the stylus (simultaneously)!

**Comment by jmontleon** [comment]
Glad to hear it!
