### ISSUE TITLE
Benign unexpected system failure

### ISSUE THREAD

**Issue by huynle** [jmontleon/pixelbook-fedora#12]
Is anyone else getting a message from the "Problem Reporting" app that shows a "system failure"?
Here is what i am getting, with a bug saying "BUG: MAX_LOCKDEP_CHAIN_HLOCKS too low!" does this have to do with a kernel config setting somewhere making the LOCKDEP values too low? 

![image](https://user-images.githubusercontent.com/2416122/147085114-ab74b286-9f31-4f9c-aca9-cb2bd641b7af.png)

the details of the bug backtrace has the following snippet

```
BUG: MAX_LOCKDEP_CHAIN_HLOCKS too low!
turning off the locking correctness validator.
Please attach the output of /proc/lock_stat to the bug report
CPU: 0 PID: 53652 Comm: lua-language-se Not tainted 5.15.10-201.pixelbook.fc35.x86_64 #1
Hardware name: Google Eve/Eve, BIOS MrChromebox-4.14 08/06/2021
Call Trace:
```

**Comment by jmontleon** [comment]
Someone reported something similar before and it was due to multiple dmesg traces. One was due to an outdated MrChomebox firmware (yours is not), another from a wifi bug that was fixed in the upstream kernel since, and possibly a third I am familiar with, but I've been disabling the module in the kernel.

dmesg output would probably help.

**Comment by jmontleon** [comment]
https://github.com/jmontleon/pixelbook-fedora/issues/5 for additional reference.

**Comment by jmontleon** [comment]
That's not pixelbook specific. Something to do with btrfs (As mentioned elsewhere I tend to stick with xfs as a personal choice).

See:
https://www.spinics.net/lists/linux-btrfs/msg111045.html

There are reports for this going back to at least 2019.

**Comment by jmontleon** [comment]
Recent BZ where someone hit it https://bugzilla.redhat.com/show_bug.cgi?id=1996507

**Comment by jmontleon** [comment]
Here it's mentioned it's usually not a real bug; also not sure it's btrfs specific even though it showed up on the ntrfs list. See some traces mentioning xfs.

https://bugzilla.redhat.com/show_bug.cgi?id=1784675#

**Comment by jmontleon** [comment]
https://yhbt.net/lore/all/CAJCQCtRrAoNtukFev8-zTHOcEYzTzxtp9ENRLkKPH4_mB882Yw@mail.gmail.com/t/

```
> >> I get the following call trace about 0.6s after dnf completes an
> >> update which I imagine deletes many files. I'll try to reproduce and
> >> get /proc/lock_stat
> >>
> >> [   95.674507] kernel: BUG: MAX_LOCKDEP_CHAIN_HLOCKS too low!
> > 
> > The message "BUG: MAX_LOCKDEP_CHAIN_HLOCKS too low" is related to
> > lockdep and not a btrfs problem, but it appears from time to time and as
> > Johannes said either increase the config variable, or ignore it.
> > 
> 
> But is not a bug if code triggers it? I.e I think it's a signal of
> misbehaving code. CC'ed PeterZ who can hopefully shed some light on this.

Maybe it's a bug, maybe it's a misconfigured build. Somebody (I don't
remember the name) asked for logs and how often it happened, that I
provided and nothing happened and the warning still shows up.
```

**Comment by huynle** [comment]
i can see that sine this is not a bug related to this project, i'll close it

**Comment by huynle** [comment]
I really appreciate your work here, and its been extremely enjoyable using my pixelbook again!

**Comment by jmontleon** [comment]
Glad to hear you are enjoying it. I like the Pixelbook hardware a lot. It's a good light system for most stuff, and being able to run a standard Linux distribution makes it superb. Hopefully my git and copr repos are a short term requirement and everything makes it upstream in the right places.
