### ISSUE TITLE
Display corruption when booting with 2 monitors attached

### ISSUE THREAD

**Issue by huang-jy** [jmontleon/pixelbook-fedora#13]
I use a setup where I have two monitors plugged into my laptop at the office. I've noticed that when I plug in both monitors and boot up Fedora, the built-in display will be corrupted. It's not noticeable until you try displaying text and you get a weird overlap:

![image](https://user-images.githubusercontent.com/2756283/148181739-b03c8134-61c2-47db-bb67-7c6d29ceedd1.png)

I've tried a few things:
1. Boot without monitors plugged in, then plug in after login: displays fine
2. Boot with both monitors (corrupt display), unplug one, wait for Fedora to update displays, then plug in again: displays fine after this
3. Boot with one monitor plugged in the plug in second after login: displays fine

So I am not sure what's happening, but it seems like with two monitors on boot, some weirdness happens with the built-in display

After monitor musical chairs:

![image](https://user-images.githubusercontent.com/2756283/148182116-a607b4a9-bc34-44f6-8d26-14e39ddf6148.png)

Monitor list if it's of any assistance:

![image](https://user-images.githubusercontent.com/2756283/148182372-02346ccd-afa1-40f4-8118-f328979addbb.png)

**Comment by jmontleon** [comment]
What if you boot with `nomodeset` on the kernel command line. If that doesn't do anything maybe the 5.16 kernel will fix things. It should be released soon and when it is I'll build it.

**Comment by huang-jy** [comment]
The resolutions are not _exactly_ the same. They're similar (I try to run with a 1400 or 1600 screen size), but this is because the pixelbook screen runs a somewhat weird aspect ratio.

**Comment by jmontleon** [comment]
I just meant the builtin display iin comparison to itself when it's working correctly vs. when it is not.

**Comment by huang-jy** [comment]
Hmmm... Good point, let me check that when I'm in the office on Monday.

**Comment by jmontleon** [comment]
I put a 5.16.0-rc8 kernel in a copr repo at https://copr.fedorainfracloud.org/coprs/jmontleon/pixelbook-test/ if you want to try that. 

I've been using a 5.16.0-rc6 kernel for awhile preparing for the release and now this and haven't noticed any issues so far.

I don't know that it will have any impact but I think the GPU driver saw a bunch of changes since 5.15. The real fix to fix for the display brightness was part of a bigger change set that finally landed so it's possible other stuff has been improved as well.

**Comment by huang-jy** [comment]
Just plugged in to the two monitor setup and logged in, and now I'm not seeing the corruption.

Resolutions are:

1: Built-in display: 1680 x 1050 (16:10), 
2: Acer Technologies 27": 1920 x 1080 (16:9)
3: Apple Computer Inc 24": 1920 x 1200 (16:10)

I wonder if it's to do with the primary display? Or perhaps one of the updates I installed over the past few days fixed whatever the issue was (I'm still on 5.15.13-201)

**Comment by jmontleon** [comment]
Interesting. Let's leave this open for a bit and you can comment back if it comes back and we can see if we can come up with some things to try. Otherwise I'll just close in a week or two.

**Comment by jmontleon** [comment]
Since I haven't heard back I'm assuming things going well. If you're still seeing problems feel tree to open this and we can try to figure something out.

**Comment by huang-jy** [comment]
Actually it does still happen, but I now just boot up with the monitors unplugged and then plug-in, or just unplug one and replug it. It's weird, and still don't know why.

Running `5.15.16-201.pixelbook.fc35.x86_64` kernel

**Comment by jmontleon** [comment]
Understood. I'm curious if 5.16 might fix it. [5.15 is an LTS](https://kernel.org/) now so it might hang around for a bit, but I expect they'll jump to 5.16 in Fedora not too long from now and I am wondering if that will provide any benefit. I've been running and using builds based on the Koji 5.16 builds and so far at least I haven't noticed any new issues. https://copr.fedorainfracloud.org/coprs/jmontleon/pixelbook-test/

**Comment by huang-jy** [comment]
Just installed 5.16 from the testing repo and not seeing the corruption so far. Will confirm when I hit the office tomorrow morning

**Comment by huang-jy** [comment]
For reference: 

```
$ uname -r
5.16.4-201.pixelbook.fc35.x86_64
```

**Comment by huang-jy** [comment]
I think we can close this. When 5.16 goes onto the stable repo it'll fix for the main userbase

**Comment by jmontleon** [comment]
Sounds good. 5.16.5 and 6 have been in the stable repo for a week or two now since Fedora 35 has moved to it. Thanks for the update and glad to hear it's working better!
