### ISSUE TITLE
automatic screen brightness never stops adjusting

### ISSUE THREAD

**Issue by robdew** [jmontleon/pixelbook-fedora#18]
Had to disable automatic screen brightness because it was constantly going up and down, like it was "hunting" for a setting.  If you open the settings panel in the upper right you can watch the brightness slider move up and down randomly.

let me know what other troubleshooting I can do to help or fix.

**Comment by jmontleon** [comment]
It's not specific to the Pixelbook. I've seen lots of complaints about it.
https://www.dell.com/community/XPS/XPS-9300-Ubuntu-amp-Adaptive-Brightness-changing-all-the-time/td-p/7515943


At least part of it is https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/issues/82

**Comment by jmontleon** [comment]
If I recall it's something like `watch cat /sys/devices/pci0000:00/0000:00:1f.0/PNP0C09:00/GOOG0004:00/cros-ec-dev.1.auto/cros-ec-sensorhub.3.auto/cros-ec-light.18.auto/iio:device2/in_illuminance_input` to watch the sensor values and you'll see it jumping all over the place, which is why you're seeing your brightness jump all over.

**Comment by jmontleon** [comment]
I would be interested to learn a way to calibrate sensor or smooth the readings so it's not like this but I haven't been able to find much other than people suggesting to turn off adaptive brightness. I've even seen people suggesting this for Chrome OS https://chromeunboxed.com/how-to-disable-auto-brightness-on-your-chromebook

**Comment by robdew** [comment]
I have no reference for what works and doesn't work outside of ChromeOS on the Pixelbook because this is the first guide that has worked for me.  I figured it was better to report than ignore.

**Comment by jmontleon** [comment]
@robdew yup, thank you for the report. I added some notes in case someone else looks, knows better, and can help improve the situation.

**Comment by jmontleon** [comment]
There's nothing to be done here for this, so I'm going to close this.

There are several PRs and issues in various open/closed states against Gnome that might one day resolve this, for example:
https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/issues/82
https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/merge_requests/237

**Comment by huang-jy** [comment]
Just to make an addition, there's an option in Power settings that allows you to turn off autoadjusting brightness.

![image](https://user-images.githubusercontent.com/2756283/193001042-379d27a7-0e32-4f2c-b90b-bf82a2a8796f.png)

Setting this off stops my screen from going bright and dark randomly based on the light level.
