### ISSUE TITLE
After running ansible playbook, power button always shuts down

### ISSUE THREAD

**Issue by mattblaha** [jmontleon/pixelbook-fedora#19]
Because of the default acpid config, GNOME's settings will get ignored, and the machine will immediately shut down.

From what I can tell, on any environment we probably don't want acpid intercepting the power button when it's installed.

**Comment by jmontleon** [comment]
Thank you for the PR! That does sound frustrating. With Xfce I bump the power now and again and I at least get prompted to shutdown so I can cancel.

I'm going to test quick on Xfce in a bit and make sure there is no unexpected degradation there and then I'll merge.

**Comment by mattblaha** [comment]
Yeah, that makes sense. From what I can tell, the acpi shut down script checks to make sure no other DE's power daemon is running, and XFCE's is in there. But it's so out of date, the default script no longer checks for GNOME's, as the process name changed years ago.

I considered making a patch to upstream, but figure on a modern install we're better off disabling that behavior by default regardless. systemd will handle the button press even if no DE is running.

**Comment by mattblaha** [comment]
You're welcome.

Thanks so much for putting this together by the way. I've had one of these for a few years, and gotten everything working tinkering around a couple of times, but things would break with updates and I couldn't use it day to day. With everything nicely packaged like this, I'm using it every day and it's *great.*

**Comment by jmontleon** [comment]
Thank you for letting me know it's getting some use and helping out. I'm happy to hear it's working for folks. I use mine most evening as well and agree it's been a great Fedora laptop.
