### ISSUE TITLE
Enabling audio disables touchpad

### ISSUE THREAD

**Issue by iancrossfield** [jmontleon/pixelbook-fedora#2]
I've been using my Linuxified Pixelbook for some time with no audio, and so was intrigued to try your suggested workaround. I followed the steps at https://github.com/jmontleon/pixelbook-fedora#Audio and rebooted, only to find that while my sound now worked -- hooray! -- my touchpad no longer responded. I've removed the new firmware files and rebooted again, to find myself once again with no sound but with a working touchpad.  

I'd be happy to post any diagnostic files that might be useful in tracking this down. Thanks for making all these resources available!

**Comment by iancrossfield** [comment]
Specifically, it seems to be either one of these two files that cause the touchpad to stop responding upon reboot:
* 9d71-GOOGLE-EVEMAX-0-tplg.bin
* dsp_fw_C75061F3-F2B2-4DCC-8F9F-82ABB4131E66.bin

The other two files (dsp_lib_dsm_core_spt_release.bin and dsmparam.bin) can be present without derailing the touchpad... but without the two files above, the sound still doesn't work on the Pixelbook.

For the record, I downloaded chromeos_14150.74.0_eve_recovery_stable-channel_mp-v2.bin.zip

**Comment by jmontleon** [comment]
It may have been coincidental. I have very rarely seen the mouse go out when booting before.

Someone else also opened an issue about it and after a reboot it started working. https://github.com/jmontleon/pixelbook-fedora/issues/1

**Comment by iancrossfield** [comment]
I was all set to dismiss that idea - but after the third reboot, both audio and touchpad are now working. Terrific, and many thanks!

The only remaining issue is that the microphone still doesn't seem to be detected - no microphone option is selectable in the system Sound settings or in various relevant applications (Zoom, etc.). See screenshot below; any thoughts?

![Screenshot from 2021-11-21 10-13-03](https://user-images.githubusercontent.com/8728644/142769854-5ca1537a-518f-415e-8bfe-6453e5626cc1.png)

**Comment by jmontleon** [comment]
The mic won't work correctly without the alsa UCM configuration.

https://github.com/jmontleon/pixelbook-fedora/tree/main/configs

You need to put  `HiFi.conf` or `kbl-r5514-5663-.conf`in `/usr/share/alsa/ucm2/kbl-r5514-5663-/` or you can install the `pixelbook-alsa-ucm` rpm package from the Copr repo if you're using Fedora.

If you want to use the mic you will probably want to use pulseaudio and not pipewire. I filed an issue but so far no response:
https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/1452

If you're using Fedora you can run `sudo dnf swap --allowerasing pipewire-pulseaudio pulseaudio` to get back to pulseaudio.

**Comment by jmontleon** [comment]
If you're not using Fedora or prefer not to use the packages you can look in the install section of the RPM Spec for any package I mention to see what it's placing where and get the unpackaged copy. Pretty much everything is just scripts or configs being copied into place, so the RPM Specs are pretty basic.

For instance for the UCM package: https://github.com/jmontleon/pixelbook-fedora/blob/main/specs/pixelbook-alsa-ucm.spec#L19-L23 (the Source1 and Source2 macros define the files above https://github.com/jmontleon/pixelbook-fedora/blob/main/specs/pixelbook-alsa-ucm.spec#L6-L7).

And those files are available here: https://github.com/jmontleon/pixelbook-fedora/tree/main/configs

**Comment by iancrossfield** [comment]
Copying  `HiFi.conf` and `kbl-r5514-5663-.conf` into  `/usr/share/alsa/ucm2/kbl-r5514-5663-/` did the trick -- I had to reboot twice, but I now have working speakers, working headphone jack, and a working internal microphone. You've fulfilled the dream I had 3 years ago when I switched this machine to Linux - many thanks!

Just for future posterity's note, I'm running Ubuntu 20.04 (as you guessed from my screenshot, above) and this is still all working. So I think your solutions here are even more general than advertised; thanks, again, for helping me track this down.

**Comment by jmontleon** [comment]
I added a note at the top for alternate distributions https://github.com/jmontleon/pixelbook-fedora#fedora-on-pixelbook

I also merged your PR (and updated it a bit to point at the new troubleshooting section)
https://github.com/jmontleon/pixelbook-fedora#audio

Added the troubleshooting and other distribution sections 
https://github.com/jmontleon/pixelbook-fedora#troubleshooting
https://github.com/jmontleon/pixelbook-fedora#other-distributions

Thanks for the report!
