### ISSUE TITLE
Enhanced Keyboard Brightness

### ISSUE THREAD

**Issue by gilphilbert** [jmontleon/pixelbook-fedora#23]
First of all - thank you for saving my Pixelbook. I love the hardware, but moved to Brave rendering the hardware useless. Your work is outstanding!

One tweak I've made is to modify the keyboard brightness script to accept either:
- No value (cycles through 0, 25, 50, 75, 100 - current behavior)
- A relative value (+10, -30)
- An absolute value (25)

This allows me to map the Alt + Screen Brightness keys to set my keyboard brightness to -10 and +10 to more closely mimic ChromeOS behavior (and many other laptops) but doesn't break the script for current installs.

Happy to open a PR to include the script if you're interested.

**Comment by jmontleon** [comment]
Yes, happy to have a PR to improve it. Thank you!

**Comment by jmontleon** [comment]
The script has been rewritten. The functionality is more or less the same with the benefit it should also work under Wayland. If you're still interested in contributing to it, feel free to reopen this. Thanks!
