### ISSUE TITLE
Slow booting and non-poweroff on mainline kernel

### ISSUE THREAD

**Issue by huang-jy** [jmontleon/pixelbook-fedora#28]
Related to #21,

Fedora now pulls the mainline kernel (in my case, `5.17.5-200.fc35.x86_64`) and, as flagged in #21, this requires blacklisting the `cros_ec_typec` module and then it is able to startup and shutdown successfully.

Held up on startup:
![image](https://user-images.githubusercontent.com/2756283/166636730-d2b53bd9-00a4-4b8a-8cd4-5b1ca6708ba1.png)

Stuck on shutdown:
![image](https://user-images.githubusercontent.com/2756283/166636690-0e3a17f8-b429-4525-9c20-ec4e858b92ec.png)

Would it be worth adding this to the ansible playbook? When the issue is resolved, the playbook can be updated to check (and remove) the blacklist accordingly?

**Comment by jmontleon** [comment]
I suppose it could be added to the playbook. Is there a reason you can't/won't update the firmware? That is the more proper fix...

**Comment by huang-jy** [comment]
Yes, updating the firmware would be the best fix, I just haven't gotten round to it yet, and I don't want to update my firmware just yet as I'm in the middle of project and want to finish that before doing something like fw updating.

**Comment by jmontleon** [comment]
Added to the ansible playbook. 9643b1674ebcbd4cae438447bddb56a3caeb52c1

Not sure there's anything else to do here so going to close this. If you disagree, please feel free to reopen it.
