### ISSUE TITLE
Update recovery file url (

### ISSUE THREAD

**Issue by EMLommers** [jmontleon/pixelbook-fedora#30]
please change in Playbook.yml the following:

 - name: Get latest recovery image information
      uri:
        url: https://cros-updates-serving.appspot.com
        return_content: true
      register: recovery_info

to:
 - name: Get latest recovery image information
      uri:
        url: https://dl.google.com/dl/edgedl/chromeos/recovery/recovery.conf?source=linux_recovery.sh
      return_content: true
      register: recovery_info

With updated link works like a charm!!!! Thank you! Running Fedora 35! All working!

**Comment by jmontleon** [comment]
288eb951a20ea0ba573536b1e1d92980a19ebc66

Thanks for the heads up!
