### ISSUE TITLE
Manjaro Audio

### ISSUE THREAD

**Issue by shadyslim2018** [jmontleon/pixelbook-fedora#31]
I followed the instruction for the audio and some of the files in recovery image wasn't there so i just copied the files from the firmware directory. I also manually copied the Hifi.conf and kbl-r5514-5663-.conf to /usr/share/alsa/ucm2/conf.d/kbl-r5514-5663-/, however, I still can't get the sound to work.

**Comment by jmontleon** [comment]
This repo is focused on Fedora and this is completely insufficient information to help.

There are specific kernel versions with broken audio so you'd need to look at the kernel version to rule that out. 
There are also specific audio modules that need to built into or as modules for the kernel. You also don't specify what version of alsa Manjaro uses so it's impossible to say if you copied those files to the correct location.

See:
https://github.com/jmontleon/pixelbook-fedora#other-distributions

Version of Manjaro, output from `dmesg`, `uname -a`, version of alsa from the package maanger, and exactly where you copied what firmware files would be  necessary at a minimum to provide some pointers, but you're largely on your own with alternate distributions.

**Comment by shadyslim2018** [comment]
Apologises, I downloaded the wrong recovery image. It's working now now that I've downloaded the correct image and copied the needed files for the sound .

I'm using Manjaro Gnome kernel version 5.17.6-1
