### ISSUE TITLE
Keyboard brightness not working

### ISSUE THREAD

**Issue by EMLommers** [jmontleon/pixelbook-fedora#32]
Really outstanding work!!!!  
The pixelbook is really the best laptop I have ever had! Especially now!
Running now kernel 5.17 and keyboard brightness is not working... installed via Ansible...

**Comment by EMLommers** [comment]
Close!!!!   Added keyboard shortcut ctrl+space to the /usr/bin/pixelbook-keyboard-backlight
Working!

**Comment by jmontleon** [comment]
Is the abbreviated setup ansible/README.md too hidden? Perhaps there needs to be a (more visible) link or something from the main README.md. I think the other day when I was reading over the main README.md it felt like this was perhaps a bit hidden, so I can do something about that if that's the case.

**Comment by EMLommers** [comment]
I completely thought it was optional... 
Maybe it could be a solution to use xbindkeys and ALT-Lightdown / ALT-LightUp?
