### ISSUE TITLE
Unable to disable power button action

### ISSUE THREAD

**Issue by JHBoricua** [jmontleon/pixelbook-fedora#37]
Is there any way to disable the pixelbook's poorly placed power button from shutting down the device? I've lost count how many times I've bumped it by accident and shut down my laptop in the middle of doing stuff. Tried setting 'Power Button Behavior' to nothing in Gnome but it is being ignored.

I've also tried setting the handle power/suspend//hibernate key to ignore on /etc/systemd/logind.conf without success.

**Comment by jmontleon** [comment]
I've no idea why this is int his section, but:
https://github.com/jmontleon/pixelbook-fedora#orientation

```
sudo mv /etc/acpi/events/powerconf /etc/acpi/events/powerconf.disabled~ This will prevent the power button from causing an immediate shutdown in Gnome.
sudo systemctl --now enable acpid
sudo systemctl restart acpid (if it's already running)
```

The playbook should also do this for you. It's Gnome specific as far as I know; something about acpid not recognizing the renamed Gnome power management utility. I don't use Gnome, but someone provided this as the workaround.

**Comment by jmontleon** [comment]
Have you had a chance to try this? If it didn't work let me know I can take some time to look when I have a few.

**Comment by JHBoricua** [comment]
I intend to as soon as I'm done with my shift at work. Will let you know later tonight.

**Comment by JHBoricua** [comment]
The above worked. I think the upgrade from 35 to 36 might have reverted the playbook changes for the above? I don't think I've ran the playbook since upgrading to 36. Thanks again.

**Comment by jmontleon** [comment]
Hopefully this is a little more durable.

https://github.com/jmontleon/pixelbook-fedora/commit/56b101b386e6243f85913e94f46e25d0afe9acd0
