### ISSUE TITLE
"cannot install the best update candidate for package pixelbook-alsa-ucm-1.0.0-4.fc35.noarch"

### ISSUE THREAD

**Issue by huang-jy** [jmontleon/pixelbook-fedora#38]
Thought I'd flag this here.

This morning, while doing my usual checking for package updates via `dnf update --refresh`, this popped up:

```
 Problem: cannot install the best update candidate for package pixelbook-alsa-ucm-1.0.0-4.fc35.noarch
  - nothing provides alsa-ucm >= 1.2.7 needed by pixelbook-alsa-ucm-1.0.0-5.fc35.noarch
...
Skipping packages with broken dependencies:
 pixelbook-alsa-ucm                       noarch                1.0.0-5.fc35                  copr:copr.fedorainfracloud.org:jmontleon:pixelbook                9.0 k

Transaction Summary
======================================================================================================================================================================
Upgrade  19 Packages

```

**Comment by jmontleon** [comment]
Hey, sorry for the noise. It looks like alsa 1.2.7 has been pushed to stable for Fedora 36:
https://bodhi.fedoraproject.org/updates/FEDORA-2022-835058a692

but not Fedora 35 yet:
https://bodhi.fedoraproject.org/updates/FEDORA-2022-d4990ace9c

in alsa 1.2.7 they layout of the ucm configuration files and what was compatible for 1.2.6 is not compatible for 1.2.7, just as what was compatible with 1.2.6 was not compatible with 1.2.5. I recieved the update on Fedora 36 last night and my sound stopped working so I built the new package.

One solution if you don't want to see this would be:
`sudo dnf clean all && sudo dnf update pixelbook-alsa-ucm --enablerepo=updates-testing`

I believe that should pull the updated packages to satisfy the new layout
