### ISSUE TITLE
Suspend resume/Hibernate resume takes long time

### ISSUE THREAD

**Issue by EMLommers** [jmontleon/pixelbook-fedora#39]
Maybe it is common.
Resuming from suspend/hibernatoine takes a lot of seconds, too much in my opinion.

Is it related to firmware or idle/suspend/hib. acpi related?

**Comment by jmontleon** [comment]
What kernel and firmware version are you running? If you haven't dealt with https://github.com/jmontleon/pixelbook-fedora/issues/26 it's most likely this issue and you should perform one of the options.

**Comment by EMLommers** [comment]
Can the cause be:
1min 68ms NetworkManager-wait-online.service
13.200s dracut-initqueue.service
  12.802s systemd-cryptsetup@luks\x2d8f572f39\x2d18fc\x2d4fdf\x2db900\x2dd89230>

Those are all above 10seconds.

**Comment by EMLommers** [comment]
I disabled NetworkManager-wait-online.service and works perfectly now!

**Comment by EMLommers** [comment]
The real solution was to remove battery and flash firmware to latest version!
Really love the Pixelbook now!!!
