### ISSUE TITLE
keyboard shortcuts: need clarification

### ISSUE THREAD

**Issue by JHBoricua** [jmontleon/pixelbook-fedora#4]
First of all, thanks for this work, just installed F35 on my Pixelbook and really looking forward to using it to its full potential. 

I'm having some difficulty setting the caps lock keyboard shortcut to the search key. I open Gnome Preferences, go to keyboard, go to shortcuts, select custom shortcut and create. At that point I give it a name, I type the command the shorcut needs to run as shown on your README file and then I click on the button to type capture the key that I want it assigned to. But when I hit the Search key it doesn't captures it no matter how many times I try, so I can't finish setting up the shortcut. Is this the correct way of doing this?

I did install the necessary rpm packages and have already rebooted. Everything else listed in your page seems to be working as expected, this is the only thing I haven't been able to set.

On that same topic, is there a way to setup the 'Google Assistant' key to function as the Super key that makes Gnome open the Activities overview?

**Comment by jmontleon** [comment]
Let me look around tonight and get back to you on both counts. My Capslock functions as a capslock but I can't remember how, so figuring out what I did is the first step; then seeing if it works in Gnome as well (I use Xfce and it may not be apples to apples).

**Comment by jmontleon** [comment]
For capslock under Gnome run: `xmodmap -e 'keysym Super_L = Caps_Lock'`

**Comment by jmontleon** [comment]
And for the Assistant key, I _think_ you're looking for `xmodmap -e 'keysym Super_R = Super_L'`

**Comment by JHBoricua** [comment]
Awesome, I'll give that a try. Thanks a bunch.

**Comment by jmontleon** [comment]
I added these as an option in the keyboard section. If it doesn't work or you need help automating it at login feel free to reopen the issue. If you want to PR clarification how to run these at startup/login that's also welcome, otherwise I'll get to it at some point.

**Comment by geroigeroi** [comment]
Sorry, I tried to write:
`xmodmap -e 'keysym Super_L = Caps_Lock'
`
and 
`xmodmap -e 'keysym Super_R = Super_L'`
and lower button works same as Alt, button on the place of Caps Lock works as Super Button, I believe (I see all windows in Gnome when I press this button).
Please advice what I must to do, I just to want that "Caps Lock" button switch Keyboard layouts.
