### ISSUE TITLE
Cannot get keyboard brightness working through Ansible install

### ISSUE THREAD

**Issue by tylerreed98** [jmontleon/pixelbook-fedora#41]
Ansible reports everything installed and was changed successfully. but even after adding the ctrl + space shortcut to the keyboard shortcuts the keyboard brightness still doesn't work. It seems ansible didn't put the script files in the correct location and the /sys/class/leds/chromeos::kbd_backlight/brightness that the keyboard brightness script refers to doesn't exist on my system. Everything else works though so I really don't know what's going on.

**Comment by jmontleon** [comment]
Which version of Fedora? What kernel version (`uname -a`)? Does `lsmod | grep backlight` return anything?
```
cros_kbd_led_backlight    16384  0
```

Also what coreboot version. I suppose if it's really old that could somehow be related.
```
$ sudo dmidecode | grep MrChromebox
	Version: MrChromebox-4.17.2
```

**Comment by tylerreed98** [comment]
I am using fedora 36 

"uname -a" returns: Linux fedora 5.18.16-200.fc36.x86_64

"lsmod | grep backlight" returns: cros_kbd_led_backlight    16384  0

coreboot version is 4.17

I suppose I should probably update coreboot and see if that fixes anything.

**Comment by tylerreed98** [comment]
All is working, I really don't know why I didn't think to update coreboot. It was so simple and I've been trying to figure this out for a week now. Thank you for the help!

**Comment by jmontleon** [comment]
You're welcome. I never used 4.17.2. I was on one of the 4.16.x versions and jumped to 4.17.2. I wonder if there was a bug with 4.17. In any case, glad updating fixed it.

**Comment by jmontleon** [comment]
Actually, I found something already. That was exactly the case.
https://www.reddit.com/r/chrultrabook/comments/vw0zkb/mrchromebox_417_07082022_changes/
