### ISSUE TITLE
Upgraded to F36, now bluetooth headphones seem stuck on mono

### ISSUE THREAD

**Issue by huang-jy** [jmontleon/pixelbook-fedora#42]
Due to some quirks with my setup, I had to upgrade to F36. Not so much an issue mostly, everything generally works. But my Bluetooth headphones seem to be stuck in mono. When running the audio test, it only shows one speaker regardless of mode (HFP/A2DP):

![image](https://user-images.githubusercontent.com/2756283/187210587-b3c3b644-2bee-4c1d-9042-9f4368cac295.png)
![image](https://user-images.githubusercontent.com/2756283/187210630-f565bb2f-ca89-4fa5-a28d-642460a0a474.png)

![image](https://user-images.githubusercontent.com/2756283/187210683-479ef379-996a-4c45-a7c0-24ae51e71349.png)
![image](https://user-images.githubusercontent.com/2756283/187210727-4dfb3a27-e78f-44f0-b66c-be9e293ff796.png)

I re-ran the ansible-playbook in case there were changes there I hadn't got but no luck.

Any ideas why I'm no longer showing dual speakers on a device that used to have it?

**Comment by huang-jy** [comment]
Additionally, after using `journalctl --follow` and watching the logs while I switched to A2DP, I see this:

```
Aug 30 09:10:27 johnny-pixelbook-fedora pulseaudio[2458]: Refused to switch profile to a2dp_sink: Not connected
```

**Comment by huang-jy** [comment]
Fixed by applying the fix described in https://askubuntu.com/questions/863930/bluetooth-headset-cant-set-a2dp-high-fidelity-playback-poor-sound-quality, namely adding

`Disable=Headset`

to `/etc/bluetooth/main.conf`, and then restarting the Bluetooth service

**Comment by jmontleon** [comment]
Good catch. I think I saw something similar with a Bluetooth headset I had on Windows. It was something like you could use the headphones and they sounded fine, but with headphone and mic there wasn't enough bandwidth so things sounded awful. It was a Logitech H800 or something and in that case it (also) had a USB dongle that allowed for using both with good quality.

**Comment by huang-jy** [comment]
Maybe you're right. Perhaps I had this on my F35 installation and the upgrade wiped the customisation.
