### ISSUE TITLE
pixelbook-acpi missing, and Steam breaks audio

### ISSUE THREAD

**Issue by olm3ca** [jmontleon/pixelbook-fedora#43]
Hi, thanks for the fantastic guide. Fedora runs so well on this hardware, with your help!

I installed Steam to test a few games and noticed it required pulseaudio. I removed it, and went through the audio steps again to get the sound working. I now have speakers, but no mic.

And now I'm getting No match for argument: pixelbook-acpi Error: Unable to find a match: pixelbook-acpi. 

Any idea why? I definitely have your repo enabled for the pixelbook, and all of the other steps are working fine. Thanks!

**Comment by olm3ca** [comment]
Oh and the Touchpad section has a small typo:
`sudo dnf -y install pixebolbook-scripts`, if you haven't already. Should be:

sudo dnf -y install pixelbook-scripts

**Comment by olm3ca** [comment]
Never mind - ran the scripts again and it's working. Sorry for the pings!

**Comment by jmontleon** [comment]
Hey @olm3ca sorry for the late response, I've been away this week. Glad to hear you sorted it out though. Thanks for the note on the typo!
