### ISSUE TITLE
kernel 5.19.9 and newer have broken wireless.

### ISSUE THREAD

**Issue by jmontleon** [jmontleon/pixelbook-fedora#44]
Reported, currently no solution: https://bugzilla.redhat.com/show_bug.cgi?id=2127753

**Comment by jmontleon** [comment]
Pretty sure it's https://bugzilla.kernel.org/show_bug.cgi?id=216497. Should be more confident shortly, finishing up a bisect, or so I hope.

And the offending commit would be:
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=linux-5.19.y&id=9516acba29e322202674d18f4dc383879f7813a5

**Comment by jmontleon** [comment]
https://lore.kernel.org/linux-iommu/YyiANMVWGc4Bvpj9@black.fi.intel.com/T/#t

**Comment by jmontleon** [comment]
4d8637f1d67242207410734844ca4b143ac5585e will fix this in 5.19.11.

https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.19.11

**Comment by huang-jy** [comment]
Thank you for the mention I will keep an eye out for the update.

**Comment by huang-jy** [comment]
5.19.11 has dropped and I can confirm wifi is now working

```
$ uname -r
5.19.11-200.fc36.x86_64
```

**Comment by jmontleon** [comment]
Awesome, thanks for checking!
