### ISSUE TITLE
2022-09-20 Package update breaks wifi

### ISSUE THREAD

**Issue by huang-jy** [jmontleon/pixelbook-fedora#45]
This morning after I applied some package updates, after rebooting, my WiFi adapter disappeared. I am currently restoring from a backup image and will report back what packages it warned to update.

I suspect maybe some firmware updates?

Since the WiFi adapter is no longer available, I cannot use the ansible playbook to reinstall the packages and drivers.

Just flagging this in case other users hit the same problem.

**Comment by huang-jy** [comment]
Found in dmesg log:

```
[ 2118.568854] iwlwifi 0000:01:00.0: Detected Intel(R) Dual Band Wireless AC 7265, REV=0x210
[ 2123.855640] iwlwifi 0000:01:00.0: Failed to load firmware chunk!
[ 2123.855650] iwlwifi 0000:01:00.0: Could not load the [0] uCode section
[ 2123.855664] iwlwifi 0000:01:00.0: Failed to start INIT ucode: -110
[ 2123.855671] iwlwifi 0000:01:00.0: Collecting data: trigger 16 fired.
[ 2124.105585] iwlwifi 0000:01:00.0: Not valid error log pointer 0x00000000 for Init uCode

```

**Comment by jmontleon** [comment]
I already have an issue open for this.
https://github.com/jmontleon/pixelbook-fedora/issues/44

And bugzilla:
https://bugzilla.redhat.com/show_bug.cgi?id=2127753

And someone already filed an upstream issue:
https://bugzilla.kernel.org/show_bug.cgi?id=216497

Others with the same problem:
https://bbs.archlinux.org/viewtopic.php?pid=2057791

I bisected it and the offending PR is being reverted. It's working it's way into mainline and stable.
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=linux-5.19.y&id=9516acba29e322202674d18f4dc383879f7813a5

Expect 5.19.10 at least to be broken as well, as it's already been cut:
https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.19.10

Conversation:
https://lore.kernel.org/linux-iommu/YyiANMVWGc4Bvpj9@black.fi.intel.com/T/#t

https://lore.kernel.org/linux-iommu/f35fd9ba-770c-7e48-a4d6-22095ea79072@linux.intel.com/T/#t

Anyway, closing as there's already an issue to cover this.

**Comment by huang-jy** [comment]
Thanks, I thought I was going crazy :smile:
