### ISSUE TITLE
eve recovery image link returns 404

### ISSUE THREAD

**Issue by ThereExistsX** [jmontleon/pixelbook-fedora#46]
A cursory search hasn't pulled up a mirror -- is there another source for this image I'm not seeing or a sound workaround?

Thank you for this great project!

**Comment by jmontleon** [comment]
Thanks for the heads up. I don't know if the site is down temporarily or permanently.

Following the playbook logic it looks like it's still downloadable at:
https://dl.google.com/dl/edgedl/chromeos/recovery/chromeos_14989.107.0_eve_recovery_stable-channel_mp-v2.bin.zip

https://github.com/jmontleon/pixelbook-fedora/blob/main/ansible/playbook.yml#L56-L65

```
$ curl -s https://dl.google.com/dl/edgedl/chromeos/recovery/recovery.conf?source=linux_recovery.sh | grep https.*eve_recovery_stable.*zip
url=https://dl.google.com/dl/edgedl/chromeos/recovery/chromeos_14989.107.0_eve_recovery_stable-channel_mp-v2.bin.zip
```

**Comment by jmontleon** [comment]
Maybe replaced by https://chromiumdash.appspot.com

**Comment by jmontleon** [comment]
https://chromiumdash.appspot.com/serving-builds?deviceCategory=Chrome%20OS

**Comment by ThereExistsX** [comment]
Your first link worked perfectly -- I now have sound!

FWIW I had tried over a few days to download the image and got 404 each time so it's probably safe to say it has moved.

Thank you so much for getting back to me so quickly -- I really appreciate it!

**Comment by jmontleon** [comment]
Glad it worked! I updated the ReadMe to save others the trouble. Thanks again for the heads up!
