### ISSUE TITLE
Sound not working on Fedora 37

### ISSUE THREAD

**Issue by saxa** [jmontleon/pixelbook-fedora#49]
Hi, I just did the upgrade to Fedora 37 few days ago and sound is no longer working. I do not see any errors in the 
dmesg or log. 
I made the upgrade through PackageKit and all went ok. Is this a known issue , anybody can help figure it out ?
I tried to redo the steps described here but no success.
Seems also that pixelbook-acpi is also no longer found by dnf.

**Comment by jmontleon** [comment]
Can you do `uname -a`? See the other open issue. A bug was introduced in 6.0. I submitted a fix upstream that is working it's way down to stable. It was added to the stable queue today. 

For now there are builds in the copr repo https://copr.fedorainfracloud.org/coprs/jmontleon/pixelbook/builds/

Make sure you have it enabled and update.

**Comment by saxa** [comment]
Hi Jason, thanks for the fast reply:
`$ uname -a
Linux rclaptop 6.0.9-300.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Nov 17 18:36:32 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

The strange thing is that in F36 before the upgrade my sound was working with the latest kernel.

**Comment by saxa** [comment]
Ok, I think that I had not the right repo enabled. I am sorry, I am new to Fedora and do not know well how to work with these repos and dnf exactly, I am coming from Slackware world.
I enabled the repo now with: 
`sudo dnf -y copr enable jmontleon/pixelbook
sudo dnf -y update`
And it seems it will update a bunch of stuff.
Let me see if after the reboot I have sound.

**Comment by saxa** [comment]
Ok, sound is again working. Seems that during the distro upgrade the pixelbook repos were disabled.
`$ uname -a
Linux rclaptop 6.0.9-301.pixelbook.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Nov 19 02:40:41 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
`
Many thanks for your nice work.

**Comment by jmontleon** [comment]
@saxa, glad to hear you got it fixed. FWIW copr repos, if you have any experience with Arch or Debian, are similar to AUR and PPA. I don't know enough about Slackware to know if it also has something similar.

We haven't been dependent on custom kernels for awhile now, so that copr repo mostly just has some helper scripts and services, however we got bit by a good one here.

**Comment by saxa** [comment]
Thanks, Slackware is nothing but all manually made, no automation like Debian, basically is all made by scripts in bash. Anyway, i can read more about how to manage repos and other stuff with dnf.
