### ISSUE TITLE
Slow resume after suspend - solution

### ISSUE THREAD

**Issue by gabrys** [jmontleon/pixelbook-fedora#50]
I'm writing this to let everyone know how to speed up resuming from suspend.

Run the following in the terminal:

```
sudo mkdir -p /etc/systemd/sleep.conf.d
sudo tee /etc/systemd/sleep.conf.d/50-freeze.conf <<< "[Sleep]"
sudo tee -a /etc/systemd/sleep.conf.d/50-freeze.conf <<< "SuspendState=freeze"
```

This creates a file /etc/systemd/sleep.conf.d/50-freeze.conf and sets its content to:

```
[Sleep]
SuspendState=freeze
```

Then reboot. This makes the resume INSTANT.

Note, your computer will use some power while sleeping> My testing showed it discharging at less than 1% per hour of sleep (8% in 12 hours, but your rate can vary depending on your battery health and other factors).

**Comment by jmontleon** [comment]
Thanks @gabrys. We can add some notes to the README.md. I think people have complained it is slow in the past so I'm sure the explanation is welcome.

**Comment by gabrys** [comment]
@jmontleon This was very annoying to me, I use the laptop as a device almost as easy to pick up as my phone, but more powerful and the resume time was really bugging me, so I started digging into the suspend options. Right now the resume experience is no worse than on ChromeOS, open the lid, enter the password, you're up :-)

The first place I went looking for an answer was "Issues" so that's where I decided to post. Hopefully more people can find this. Adding to README would work as well, obviously, given this is worth mentioning.

I still want to gather more data on the discharge rate while frozen, so far this looks really good, but I'd like to leave the laptop frozen for ~10 hours and record the state of charge before and after to give a %/hr figure.

I would also like to dig into the sleep-then-hibernate mode to see if it's working at all (in ancient times this required a swap partition and some grub settings, I'm not sure how this is done nowadays...), and if resuming from hibernation is any quick.

Combining the findings from the two points above we could decide on settings that will allow instant resumes for most suspends and hibernation for longer ones to preserve the power. (Maybe freeze -> wait 24hr -> hibernate if the discharge rate is small and the resume from hibernation is reasonable?).

I'll keep you posted.

Cheers,
Piotr

**Comment by gabrys** [comment]
(I'm gonna be editing this comment with new data)

Sleep for 75 minutes: battery down 1% (93% → 92%)

**Comment by jmontleon** [comment]
If you'd like to submit a PR or changes feel free to do so and / or reopen

**Comment by jmontleon** [comment]
@gabrys are you able to narrow it down any? I think Fedora has been on 6.3 kernels since 6.3.4. Did any of the prior 6.3 kernels work? What about 6.2.15? 

Are you on the most recent MrChromeBox.tech firmware release (4.20)?
https://mrchromebox.tech/

I don't see much recent and interesting on the kernel regression list. Just one for libata locking up on sr devices. Not sure how that would apply unless it's affecting other classes of devices, or you have additional hardware attached when it's failing. https://lore.kernel.org/regressions/7a3b3a7e-cf69-a60a-8790-59ca4393292b@jmbreuer.net/

I can try play around later and see if I can suspend/resume. Once we have a little more info we should probably open a new issue even if we don't have an actual answer.

**Comment by gabrys** [comment]
I had two other kernels to choose from. Tested 6.1.x-fc37 and the issue was still happening. So I think, oddly, this must be something in the user space

**Comment by jmontleon** [comment]
FWIW I was able to suspend and resume without any apparent issue when I tried just now.

**Comment by gabrys** [comment]
Correction, with `SuspendState=freeze` it works OK! Turns out I had the header commented out as well.

**Comment by jmontleon** [comment]
Glad you got to the bottom of it. It is curious that you have to set this though. Looking at `/etc/systemd/sleep.conf` on my system the only thing not commented is the line `[Sleep]`.
