### ISSUE TITLE
pixelbook-alsa-ucm on slackware

### ISSUE THREAD

**Issue by saxa** [jmontleon/pixelbook-fedora#53]
Hi Jason, I will keep this seprated if for you does not make any difference. 
I installed right now on my slackware install the pixelbook-alsa-ucm files as per your spec file. I can say that at first look it does not make any difference.
Sound continues amplified as before.
But I think , I am not sure, but will confirm that later, when I have not those files installed the headphones get sound and main speakers get muted. As said I will play with this a bit and will keep this separated from the no sound bug.

**Comment by saxa** [comment]
Another thing is why the name of the directory is kbl-5514-5663- and not kbl-5514-5663-max ? Also I saw that on my slackware install I have the kblrt5660 without any dashes in the middle. Is it possible that the dashes make some difference ?

**Comment by saxa** [comment]
Ok, just to confirm, plugging in the headphones does NOT mute the audio even without the HiFi.conf and kbl-r5514-5663-.conf files.

**Comment by jmontleon** [comment]
This is known. https://www.alsa-project.org/wiki/ASoC

"There is no standard method to signal user initiated audio events. e.g. Headphone/Mic insertion, Headphone/Mic detection after an insertion event. These are quite common events on portable devices and often require machine specific code to re route audio, enable amps etc after such an event."

As I understand it the audio system has no way to trigger events  to swap inputs and outputs when you plug in the headphones.

We do get acpi events though and trigger off that to simulate the functionality. 

https://github.com/jmontleon/pixelbook-fedora/blob/main/scripts/pixelbook-acpi#L38-L44

**Comment by saxa** [comment]
Ok, many thanks, I will work on that these days, but firstly I need to educate myself about it. Although I can say that even on my Fedora install the plug in of the headphones does not work correctly. I hear both speakers and headphones. I will check tomorrow on my fedora install if I have pixelbook-acpi installed. I think I have it.

**Comment by lyncolnmd** [comment]
> Ok, many thanks, I will work on that these days, but firstly I need to educate myself about it. Although I can say that even on my Fedora install the plug in of the headphones does not work correctly. I hear both speakers and headphones. I will check tomorrow on my fedora install if I have pixelbook-acpi installed. I think I have it.

Does the HDMI/DP audio out work with Slackware? Ive only gotten it working on Ubuntu

**Comment by saxa** [comment]
I have not tried that neither in Fedora or Slackware, I have to buy a cable to try that or the adapter, as I only have plain HDMI cables at home. Or is there some other way to go around it ?

**Comment by lyncolnmd** [comment]
You can test the DP out (i think DP out is HDMI1) where you use a USB-C to display port cable or you can use the usb c to hdmi adapter and use a regular HDMI cord (i think thats HDMI 2) to test it. It works perfectly in Linux Mint and Ubuntu 22.04 but those come with pulse installed by default so i dont know if there is a component of pulse missing. I tried to compare it by running arch on the LTS kernel but the HDMI/DP out did not work on Arch. The UCM2 configs seem fine so i dunno why this behavior happens. I gave never got it successfully working on Fedora and honestly its the singular thing not working out of the box for me right now. Everything else (including keyboard brightness) works ootb until audio broke in 6.1

**Comment by saxa** [comment]
Ok, I can confirm that Slacware comes with both pulseaudio and pipewire, usually PA as default.
For the HDMI I will try to arrange some USB-C to HDMI adapter and test that. But need to see when 
I have some time to pass near a shop where they sell these. 

For me the UCM2 configs does not seem to make any difference at all , at least in Slackware. But I need to figure out if Slackware paths are the same ones as in Fedora.

**Comment by jmontleon** [comment]
What kernel are you using on slackware that has reliable audio to test with this? I saw you say 6.1.8 worked, then didn't. I'm curious.

to your question, "kbl-5514-5663- and not kbl-5514-5663-max" from dmesg:
`[    7.891565] kbl_r5514_5663_max kbl_r5514_5663_max: ASoC: driver name too long 'kbl-r5514-5663-max' -> 'kbl-r5514-5663-'`

**Comment by lyncolnmd** [comment]
If i read the arch wiki right, theres a particular package that allows Pulseaudio to use the alsa ucm2 configurations. Honestly that whole section is very touchy. Literally one thing out of place breaks the entire ucm config then it defaults to the baseline where it shows only headphone output but it does give sound. I do need to give Slackware a try though...ill run my ansible on it and see what happens. Right now i have arch installed

**Comment by saxa** [comment]
I am on stock slackware kernel supplied by Slackware64-current tree. This is 6.1.8 as of today. Yes there is sometimes issues with sound not working, but I have not understood it why and how it happens to stop. Although in the most cases I tested it it works. I think only once happened in theses days that was not working when booted the laptop.

**Comment by saxa** [comment]
@lyncolnmd, yes afaik Pulseaudio should set itself up by reading alsas UCM. At least this is what I read yesterday.

**Comment by saxa** [comment]
> to your question, "kbl-5514-5663- and not kbl-5514-5663-max" from dmesg: `[ 7.891565] kbl_r5514_5663_max kbl_r5514_5663_max: ASoC: driver name too long 'kbl-r5514-5663-max' -> 'kbl-r5514-5663-'`
Ok, thanks Jason, but this maybe be the thing ? When you issue aplay -l the driver name is the complete name
with -max at the end in the  square brackets. So Alsa is seeing it as a full name. Just supposing.

**Comment by saxa** [comment]
This is what I get in my Fedora:
`$ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: kblr55145663max [kbl-r5514-5663-max], device 0: Audio (*) []
  Subdevices: 0/1
  Subdevice #0: subdevice #0
card 0: kblr55145663max [kbl-r5514-5663-max], device 2: Headset Audio (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: kblr55145663max [kbl-r5514-5663-max], device 6: Hdmi1 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: kblr55145663max [kbl-r5514-5663-max], device 7: Hdmi2 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
`

But iirc also on slackware too.

**Comment by saxa** [comment]
Ok, one thing you can try is the live slackware from Alienbob.

**Comment by jmontleon** [comment]
@saxa I have built a vanilla unpatched 6.1.8 kernel and booted on Fedora with no audio, so hearing that Slackware more or less works is... interesting. I tried disabling selinux as well, thinking it might be blocking something awhile ago, but no dice there either.

What version of alsa do you have on slackware?

**Comment by saxa** [comment]
Hi Jason, yup, interesting. I think you can take a look here:
'http://www.slackware.com/changelog/current.php?cpu=x86_64'

Alsa version is alsa-utils-1.2.8-x86_64-1.txz and alsa-lib-1.2.8-x86_64-1.txz.

**Comment by jmontleon** [comment]
@saxa what was your process for install 6.1.8 on slackware. i have slacware 15 and updated, but it's still a 5.15 kernel it looks like. Trying to reproduce your functional environment.

**Comment by saxa** [comment]
@jmontleon please use slackpkg tool as follows, as if you are on 5.15.x series you installed Slackware 15.0 but I am on current. If I remeber both Slackware 15 and -current had a working sound ouf of the box.
So you have to update to current as follows:

Change the line in /etc/slackpkg/mirrors to point to slackware64-current/ tree.
Do the following commands:
`# slackpkg update`
`# slackpkg upgrade-all`
`# slackpkg install-new`
`# slackpkg clean-system`

This should bring you to the state my pixelbook is. Reboot and you should be running the latest -current.
If you need any help with commands let me know.

**Comment by saxa** [comment]
@jmontleon yes you need to install -current, but no need to reinstall everything, just upgrade frm 15 to -current, as in slackware current is always what next release will be, so its an update from 15.0 release.
So simply use slackpkg tool to sync to the current packages tree.

**Comment by jmontleon** [comment]
Do you have pulseaudio installed. Are you using it? Does `aplay -l` output hang for you?

6.1.9 behaves as badly for me on slackware as it does on any other distro.

**Comment by saxa** [comment]
Yes I have all packages installed from Slackware64-current tree, meaning pulseaudio and pipewire. By default Slackware ships pulseaudio enabled audio. And enabling pipewire (enable-pipewire.sh is the command) sound does not work. I tested this. And aplay -l never hanged at all, I issue aplay -l and it does list the audio interfaces immediately.

**Comment by saxa** [comment]
I really think this is not much related to the kernels but the configuration, just a gues although.

**Comment by jmontleon** [comment]
What configuration? If I place the topology and firmware files audio doesn't work, pulseaudio and aplay lock up. It doesn't matter if I add the ucm configuration files or not. Topology and firmware files are required for the card to work, so I don't know how we could be doing anything different.

You are placing these?
- /opt/google/dsm/dsmparam.bin
- /lib/firmware/9d71-GOOGLE-EVEMAX-0-tplg.bin
- /lib/firmware/dsp_lib_dsm_core_spt_release.bin
- /lib/firmware/intel/dsp_fw_C75061F3-F2B2-4DCC-8F9F-82ABB4131E66.bin

Are the md5sums for any or all of these:
```
2e0a0abe759730aed589cfef6db0c61f  /opt/google/dsm/dsmparam.bin
df048e60442e7d5fc17c2799936753b3  /lib/firmware//9d71-GOOGLE-EVEMAX-0-tplg.bin
256da2c7e6099662865c3e6d5845e68a  /lib/firmware/dsp_lib_dsm_core_spt_release.bin
121049a4bed67e34dd0af5d01b667fb3  /lib/firmware/intel/dsp_fw_C75061F3-F2B2-4DCC-8F9F-82ABB4131E66.bin
```

**Comment by jmontleon** [comment]
What does `uname -r` show?

**Comment by saxa** [comment]
First thing, make sure your user is part of the audio group. You created the user with adduser or are you directly using root account ?

Now lets go to the answers:
> What configuration? 
Thats a good question. I have no idea how kernel and alsa internally work. 

> If I place the topology and firmware files audio doesn't work, pulseaudio and aplay lock up. 
By locking what exactly you mean ? They do not play or they take long to show the output ?
If I do aplay -l it shows me immediately the following:
`sasa@goopix:~$ aplay -l`
`**** List of PLAYBACK Hardware Devices ****`
`card 0: kblr55145663max [kbl-r5514-5663-max], device 0: Audio (*) []`
`  Subdevices: 1/1`
`  Subdevice #0: subdevice #0`
`card 0: kblr55145663max [kbl-r5514-5663-max], device 2: Headset Audio (*) []`
`  Subdevices: 1/1`
`  Subdevice #0: subdevice #0`
`card 0: kblr55145663max [kbl-r5514-5663-max], device 6: Hdmi1 (*) []`
`  Subdevices: 1/1`
`  Subdevice #0: subdevice #0`
`card 0: kblr55145663max [kbl-r5514-5663-max], device 7: Hdmi2 (*) []`
`  Subdevices: 1/1`
`  Subdevice #0: subdevice #0`
`sasa@goopix:~$` 
``

>It doesn't matter if I add the ucm configuration files or not. Topology and firmware files are required for the card to work, so I don't know how we could be doing anything different.

I think ucm doesnt matter at all as here its working without it.
> 
> You are placing these?
> 
>     * /opt/google/dsm/dsmparam.bin
> 
>     * /lib/firmware/9d71-GOOGLE-EVEMAX-0-tplg.bin
> 
>     * /lib/firmware/dsp_lib_dsm_core_spt_release.bin
> 
>     * /lib/firmware/intel/dsp_fw_C75061F3-F2B2-4DCC-8F9F-82ABB4131E66.bin
> 
Yes correct, as per your instructions from point 1 to 5.

> 
> Are the md5sums for any or all of these:
> 
> ```
> 2e0a0abe759730aed589cfef6db0c61f  /opt/google/dsm/dsmparam.bin
> df048e60442e7d5fc17c2799936753b3  /lib/firmware//9d71-GOOGLE-EVEMAX-0-tplg.bin
> 256da2c7e6099662865c3e6d5845e68a  /lib/firmware/dsp_lib_dsm_core_spt_release.bin
> 121049a4bed67e34dd0af5d01b667fb3  /lib/firmware/intel/dsp_fw_C75061F3-F2B2-4DCC-8F9F-82ABB4131E66.bin
> ```
Here are the md5sums:
`2e0a0abe759730aed589cfef6db0c61f  /opt/google/dsm/dsmparam.bin`
`df048e60442e7d5fc17c2799936753b3  /lib/firmware/9d71-GOOGLE-EVEMAX-0-tplg.bin`
`256da2c7e6099662865c3e6d5845e68a  /lib/firmware/dsp_lib_dsm_core_spt_release.bin`
`121049a4bed67e34dd0af5d01b667fb3  /lib/firmware/intel/dsp_fw_C75061F3-F2B2-4DCC-8F9F-82ABB4131E66.bin`

And the uname -r gives the following output:
`sasa@goopix:~$ uname -r`
`6.1.9`
`sasa@goopix:~$ `

**Comment by saxa** [comment]
Ok, I just saw that slackware64-current tree has now a new 6.1.10 kernel, upgraded right now, and also on this kernel for me the sound works. I can watch streams , listen youtube , so i believe also other things related to sound work.

I dont know if this can help but output of amixer -c 0 on my slackware install is attached here.
[amixer.txt](https://github.com/jmontleon/pixelbook-fedora/files/10670470/amixer.txt)
[amixer_controls.txt](https://github.com/jmontleon/pixelbook-fedora/files/10670476/amixer_controls.txt)
[amixer_scontrols.txt](https://github.com/jmontleon/pixelbook-fedora/files/10670478/amixer_scontrols.txt)

**Comment by jmontleon** [comment]
Thanks, I'll look through. FWIW, alsa ucm isn't needed to hear audio, but you won't see all the inputs outputs properly. The audio is also quite loud without the UCM configuration.

Without UCM configuration:
![image](https://user-images.githubusercontent.com/1850500/217122408-63e2834c-cbf8-483a-9a10-b78268f04309.png)

With:
![image](https://user-images.githubusercontent.com/1850500/217122451-c21f60e2-c9f3-42ce-8826-d9eb88ce3747.png)

**Comment by jmontleon** [comment]
Any chance you're on an older coreboot release?

```
$ sudo dmidecode | grep -i MrC
	Version: MrChromebox-4.19

```

**Comment by saxa** [comment]
> Any chance you're on an older coreboot release?
> 
> ```
> $ sudo dmidecode | grep -i MrC
> 	Version: MrChromebox-4.19
> ```

I have nothing showed with this. I dont remember which version I have installed, surely is not the latest.
[dmidecode_slackware.txt](https://github.com/jmontleon/pixelbook-fedora/files/10670551/dmidecode_slackware.txt)

I attach also my dmesg and lsmod if you can get any good info from it.
[dmesg_6.1.10.txt](https://github.com/jmontleon/pixelbook-fedora/files/10670556/dmesg_6.1.10.txt)
[lsmod_6.1.10.txt](https://github.com/jmontleon/pixelbook-fedora/files/10670557/lsmod_6.1.10.txt)

**Comment by saxa** [comment]
I have a slightly different pavucontrol output and configuration tabs.
![pavucontrol](https://user-images.githubusercontent.com/1041629/217124307-ea8323a6-f9f9-4ea6-9f64-d5505c42161a.png)
![pavucontrol_conf](https://user-images.githubusercontent.com/1041629/217124318-6d561fa9-a5e9-43c2-b98d-04097731c9ce.png)

**Comment by jmontleon** [comment]
Right, that closely resembles the first picture I pasted above without UCM configured.

The second is what you'd see instead if UCM was configured.

Are you using legacy boot mode to BIOS boot rather than EFI?
https://mrchromebox.tech/#bootmodes

```
BIOS Information
	Vendor: coreboot
	Version: Google_Eve.9584.230.0
	Release Date: 09/06/2021
```

**Comment by saxa** [comment]
Yes I am in legacy BIOS mode as I have not done the complete rewrite to UEFI. So I have to press every time CTRL-L at boot.

**Comment by saxa** [comment]
When I start the computer it writes SeaBIOS iirc.

**Comment by jmontleon** [comment]
OK, BIOS vs UEFI is a big difference that could come into play.

coreboot from 9/6/2021 vs now is also big and probably a little easier to test.  I'll dig up the process and give it a try.

**Comment by saxa** [comment]
Ok, but I can confirm that on both machines I use SeaBIOS, as I was someway scarred to go flashing it with UEFI, since maybe I decide to sell the machine and I can reainstall ChromeOS, that was basically the main reason why not going with full UEFI from Coreboot.

**Comment by jmontleon** [comment]
You can use the menu options in the firmware utility script to backup and restore the original firmware. You get a file like `stock-firmware-EVE-20210719.rom`.

In the event you want to go back to ChromeOS you throw the file on a thumb drive and use the restore option. Just don't lose it! Although I'd be loathe to suggest updating or changing if audio is working now.

What version is installed on your one with Fedora where you've experienced problems?

**Comment by saxa** [comment]
In fact the thing works ok, so surely I wont go changeing it, and yes, one of the reasons is that then I forget where I stored this backup pen drive.... you know I am 50 already :D .
Anyway the SeaBios on my fedora pixelbook will post it tomorrow.

**Comment by jmontleon** [comment]
If audio is broken on the Pixelbook with Fedora (at least without the workaround kernels), it would be interesting if you are able and want to give a try installing Slackware on a thumb drive and seeing if it similarly misbehaves. There would be a strong possibility that the problem exists between newer versions of coreboot and the kernel if the problem reproduces there. Likewise I suppose if you got Fedora working on the other with slackware currently. 

I think I mentioned it, but it would not be the first time coreboot versions+kernel versions combinations misbehaved, the cros ec type c driver being an example.

**Comment by saxa** [comment]
I can try to run a live slackware on my fedora pixelbook and fedora live on my slackware one. Thats no problem, will prepare the usb drives. But I think I will have to install the firmware in some way to be loded.
Anyway, here is the dmidecode and biosdecode on my fedora pixelbook.
[dmidecode_biosdecode_fedora.txt](https://github.com/jmontleon/pixelbook-fedora/files/10674246/dmidecode_biosdecode_fedora.txt)

**Comment by saxa** [comment]
I just started my fedora install right now and I have no audio at the moment. But aplay -l lists the 
interfaces and on the control panel I have only dummy driver.
See dmesg and aplay -l out.
[dmesg_fedora.txt](https://github.com/jmontleon/pixelbook-fedora/files/10674297/dmesg_fedora.txt)
`6.1.9-201.pixelbook.fc37.x86_64`

**Comment by saxa** [comment]
Yup, thanks for the help. I created my install scripts and sincerely this does not make any hearable change on Slackware, although I have the ucm stuff installed all is working same way as without UCM installed.
