### ISSUE TITLE
6.1.8 kernel panics on boot

### ISSUE THREAD

**Issue by huang-jy** [jmontleon/pixelbook-fedora#54]
Reference to #51 and to put it here

Basically under 6.1.8 (both stock, and the copr version), the kernel panics. By removing `rhgb quiet` on the kernel switches, we see this (this was from stock)

![image](https://user-images.githubusercontent.com/2756283/215409941-c9ef0959-9f92-4d65-9f8e-cff6fb7391b4.png)

I just checked my boot partition sizes:

```
/dev/nvme0n1p2                           974M  227M  681M  25% /boot
/dev/nvme0n1p1                           599M   18M  582M   3% /boot/efi
```

So should be plenty of space for kernel stuff there.

I'm just trying to setup a kernel build environment locally then I might try building my own kernels and bisecting.

EDIT: One thought I had though. Perhaps 6.1.8 assumes a btrfs file system (I chose lvm during install) and that might be confusing it.

**Comment by jmontleon** [comment]
FWIW, I use xfs (which the server iso defaults to) on lvm and it boots. If 6.1.7 works and 6.1.8 does not, fortunately the number of commits is probably fairly small.

**Comment by huang-jy** [comment]
I'll try to install 6.1.7 later and see if it does work and let you know. If it does, then we know where to start hunting.

On a semi-related side note: I'm figuring out the bisecting functionality of git. In the kernel source tree, how do I find the release of (for example) 6.1.7?  There's tags for 6.0, 6.1, and the various rc versions, but no tags for the patch versions (e.g. 6.1.7) . So if, for example, 6.1.7 was good and 6.1.8 was bad, how would I find the commit related to the 6.1.7 release?

**Comment by jmontleon** [comment]
v6.1.7 v6.1.8 etc.

**Comment by huang-jy** [comment]
Can you confirm which repo you're using for source? 

https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git
or
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git

**Comment by jmontleon** [comment]
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git

**Comment by huang-jy** [comment]
Perfect, thanks.

**Comment by huang-jy** [comment]
Dangit it looks like the fedora repos only keep the latest kernel version so I can't install 6.1.7. I presume I'll have to download off koji? https://koji.fedoraproject.org/koji/buildinfo?buildID=2112328

**Comment by huang-jy** [comment]
It does appear that way, I'll pick up the koji ones and report back.

**Comment by huang-jy** [comment]
`6.1.10-201.pixelbook.fc36.x86_64` just dropped and does not kernel panic. I will close this issue
