### ISSUE TITLE
Fedora and Legacy boot audio may not be working

### ISSUE THREAD

**Issue by jmontleon** [jmontleon/pixelbook-fedora#57]
@saxa when you have time on your Fedora system can you reboot and share your dmesg out?

Also can you share the output of `ls /etc/modprobe.d` and `aplay -l`?

Maybe we can get to the bottom of what's going on.

**Comment by saxa** [comment]
Absolutely, here they are. Hope it helps you. But the traces I see on both machines are the same as 
they are also in issue #56 dmesg.txt . I see pulseaudio seems to be causing this.
[aplay_fedora_kernel-6.2.7.txt](https://github.com/jmontleon/pixelbook-fedora/files/11061107/aplay_fedora_kernel-6.2.7.txt)
[dmesg_fedora_kernel-6.2.7.txt](https://github.com/jmontleon/pixelbook-fedora/files/11061108/dmesg_fedora_kernel-6.2.7.txt)
[modulesdir_fedora_kernel-6.2.7.txt](https://github.com/jmontleon/pixelbook-fedora/files/11061112/modulesdir_fedora_kernel-6.2.7.txt)

**Comment by jmontleon** [comment]
What traces are you referring to? It doesn't look at all similar. Your card is showing up. In 56 he's seeing a glitch with rt5514 in dmesg. There's no such error in your dmesg. As far as I can tell so far your card is configured and working properly and they don't look at all similar.

Do you have the Speakers selected in Gnome/Xfce/whatever as the output?

If so can you run `systemctl -t service --user` and paste the output?

**Comment by saxa** [comment]
> What traces are you referring to? It doesn't look at all similar.
See from this line below in the dmesg.
[   15.577647] ------------[ cut here ]------------

**Comment by saxa** [comment]
> Do you have the Speakers selected in Gnome/Xfce/whatever as the output?

Yes I have them selected. 
![Screenshot from 2023-03-24 14-39-46](https://user-images.githubusercontent.com/1041629/227536670-63e8163b-1d0d-41b7-bf45-3f5310550e62.png)


> If so can you run `systemctl -t service --user` and paste the output?

Absolutely yes, here it is:
[systemctl_service.txt](https://github.com/jmontleon/pixelbook-fedora/files/11062680/systemctl_service.txt)

**Comment by jmontleon** [comment]
```
  pipewire.service                                         loaded active running PipeWire Multimedia Service
  pixelbook-acpi.service                                   loaded active running Listen to ACPI events relevant to Pixelbook hardware and act on them0
  pixelbook-display-orientation.service                    loaded active running Monitor Pixelbook Display Orientation
  pulseaudio.service                                       loaded active running Sound Service
```

You have pipewire running. It should not be. It may be as simple as that.

Run through step 6, make sure the pipewire package is not installed when done.
https://github.com/jmontleon/pixelbook-fedora#audio

`rpm -qa | grep pipewire` shouldn't return any more than libs, media-session, and maybe devel and depending what you have need for.
```
pipewire-media-session-0.4.2-1.fc38.x86_64
pipewire-libs-0.3.67-1.fc38.x86_64
pipewire-devel-0.3.67-1.fc38.x86_64
```

Once cleaned up reboot and see if there's any change. If not lets see `systemctl -t service --user` output and `rpm -qa` output.

**Comment by saxa** [comment]
Oh, f@#K , stupid me, I was testing some things and forgot about that thing. Sorry to bother, really sorry, please excuse me Jason.

**Comment by jmontleon** [comment]
Cool, glad it's working!
