### ISSUE TITLE
Setup pipewire for a working audio.

### ISSUE THREAD

**Issue by saxa** [jmontleon/pixelbook-fedora#60]
Hi all, I have been tweaking a bit with my slackware install to make audio work with pipewire.
So all in all I have now a working pipewire audio also on my fedora install.

The fix is simple. I have talked to the pipewire devs and the whole thing seems problematic as pulseaudio works with 16 bits only and pipewire internally is working with 32 bits. So as suggested by the main pipewire developer
ir is enought to force pipewire to work with 16 bits. To do this edit the following file:

`/usr/share/pipewire/media-session.d/alsa-monitor.conf`
and uncomment the line
`audio.format = "S16LE"`

If you use wireplumber the file is in:
`/usr/share/wireplumber/main.lua.d/50-alsa-config.lua`
and uncomment the line `["audio.format"] = "S16LE"` by removing the double dash `--` in front of it.

Restart or logout and relogin and you should have a perfectly clear sound. I tried also a skype call
and my microfone has no noise at all.

Its probably better to make this configurations in `/etc/pipewire/` as during future upgrades will stay there. 

If you want to see the full discussion you can get it here on the pipewire gitlab issue [3116](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/3116#note_1845418)

Thats it, enjoy.

**Comment by jmontleon** [comment]
Thanks @saxa! Fantastic! I will give this a try and update the docs when I have a few to reproduce.

**Comment by jmontleon** [comment]
I think we want to add a section to match _just_ our card so we don't mess with docks, usb audio, and other devices.

I was only able to get it to work somewhat correctly (the device names were screwed up but audio worked) by trying to add just the one match in a file alone.

Instead what I did is `sudo cp /usr/share/wireplumber/main.lua.d/50-alsa-config.lua /etc/wireplumber/main.lua.d/50-alsa-config.lua` and add a section to the bottom just inside the last close brace.
```
  {
    matches = {
      {
        { "node.name", "matches", "alsa_input.platform-kbl_r5514_5663_max.*" },
      },
      {
        { "node.name", "matches", "alsa_output.platform-kbl_r5514_5663_max.*" },
      },
    },
    apply_properties = {
      ["audio.format"] = "S16LE"
    },
  },
```

That seems to work well...

**Comment by saxa** [comment]
Seems ok and reasonable to me to add something like that. Although I want to play a bit more with it.
I have still pipewire-media-session here on my machine and audio stopped right now, have no idea for what reason, but will investigate more about it.

**Comment by jmontleon** [comment]
Is there any reason at all to favor media-session over wireplumber if media-session is deprecated? It seems like the preference should be the newer and supported option.

**Comment by saxa** [comment]
> Is there any reason at all to favor media-session over wireplumber if media-session is deprecated? It seems like the preference should be the newer and supported option.

@jmontleon exactly, but I have no clue why I had it on my machine. I removed it and installed wireplumber and for some reason fedora was switching back to previous system config it seems but re-enable pulseaudio, bahh, who knows what was on. It fixed now and with pipewire works ok all audio.

**Comment by jmontleon** [comment]
You had it because we were swapping it in for the sake of pulseaudio:
```
Replace pipewire with pulseaudio to fix a mic noise [issue](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/1452)
sudo dnf swap --allowerasing pipewire-pulseaudio pulseaudio
sudo dnf swap wireplumber pipewire-media-session
sudo dnf swap pipewire-jack-audio-connection-kit jack-audio-connection-kit
sudo dnf remove pipewire-alsa
```

You'd basically want to do these in reverse and ensure a few other packages are installed to get to a good pipewire state.

You can swap cleanly between the two with the ansible playbook now:  
`ansible-playbook -K playbook.yml` will get you to wireplumber.  
`ansible-playbook -K playbook.yml -e sound_server=pulseaudio` to go (back) to pulseaudio.  

If you needed to simulate it by hand for some reason you can see what the playbook is doing for either:
https://github.com/jmontleon/pixelbook-fedora/blob/main/ansible/playbook.yml#L149-L200

I ran / rebooted back and forth a few times and have working audio with either.
