### ISSUE TITLE
Replace chromebook search with capslock

### ISSUE THREAD

**Issue by saxa** [jmontleon/pixelbook-fedora#62]
Hi not exactly an issue, but I would like to know if somebody has been able to make the google chrome search button remapped to a functional caps-lock ?

I have been able so far only to make the key between left ctrl and alt to behave like the mouse pointer in the hot corner.

For me the tips like explained in [keyboard](https://github.com/jmontleon/pixelbook-fedora#capslock) section does not work.
Any tips ?

**Comment by ntcarlson** [comment]
The search key's function is defined in [`/lib/udev/hwdb.d/61-eve-keyboard.hwdb`](https://github.com/jmontleon/pixelbook-fedora/blob/5d155e8529fba7f43db67e8a407723a1c69c3e42/configs/61-eve-keyboard.hwdb#L10). The keycode is `db` and is mapped to `leftmeta` by default, but you can change it to `capslock` instead. After editing the file, you can apply the changes immediately with

```
systemd-hwdb update
udevadm control --reload-rules
udevadm trigger
```

At least for me, that is all that was necessary to turn the search key into capslock. No `xmodmap` or custom keyboard shortcuts were required.

**Comment by jmontleon** [comment]
The suggestion by @ntcarlson above seems sensible. There are some other possibilities here. 
https://github.com/jmontleon/pixelbook-fedora#keyboard

It shouldn't be difficult one way or another to make it work as a Capslock.

**Comment by saxa** [comment]
@ntcarlson many thanks, that worked out perfectly !!!
I was struggling with this a long time, tried so many different options, and no one worked.
@jmontleon thanks for that link, but those have not worked for me at all.
