### ISSUE TITLE
Kernel backtraces

### ISSUE THREAD

**Issue by saxa** [jmontleon/pixelbook-fedora#64]
Hi, I am getting all the time the following when I boot the machine:

WARNING: CPU: 2 PID: 1319 at sound/soc/intel/skylake/skl-messages.c:552 skl_init_module+0x842/0x860 [snd_soc_skl]
Modules linked in: snd_seq_dummy snd_hrtimer nf_nat_ftp nf_conntrack_ftp nf_conntrack_netbios_ns nf_conntrack_broadcast nft_fib_inet nft_fib_ipv4 nft_fib_ipv6 nft_fib nft_reject_inet nf_reject_ipv4 nf_reject_ipv6 nft_reject nft_ct nft_chain_nat nf_nat nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 ip_set nf_tables nfnetlink qrtr bnep i2c_hid_acpi i2c_hid snd_soc_kbl_rt5663_rt5514_max98927 snd_soc_skl_ssp_clk snd_sof_pci_intel_skl snd_sof_intel_hda_common soundwire_intel cros_ec_light_prox cros_ec_sensors soundwire_generic_allocation cros_ec_sensors_core soundwire_cadence industrialio_triggered_buffer snd_sof_intel_hda kfifo_buf industrialio snd_sof_pci snd_sof_xtensa_dsp snd_soc_hdac_hdmi cros_ec_sysfs snd_sof snd_soc_dmic cros_ec_chardev snd_sof_utils soundwire_bus cros_usbpd_logger iwlmvm cros_usbpd_charger cros_ec_sensorhub iTCO_wdt intel_tcc_cooling x86_pkg_temp_thermal intel_pmc_bxt iTCO_vendor_support snd_soc_avs intel_powerclamp mac80211 intel_rapl_msr snd_soc_hda_codec
 coretemp snd_soc_skl kvm_intel snd_soc_hdac_hda snd_hda_ext_core snd_soc_sst_ipc cros_ec_dev snd_soc_sst_dsp sunrpc libarc4 snd_soc_acpi_intel_match kvm iwlwifi snd_soc_acpi uvcvideo irqbypass videobuf2_vmalloc videobuf2_memops videobuf2_v4l2 rapl snd_hda_intel btusb snd_intel_dspcfg snd_intel_sdw_acpi btrtl intel_cstate videobuf2_common btbcm cfg80211 snd_hda_codec intel_uncore btintel videodev btmtk snd_hda_core pcspkr binfmt_misc mc bluetooth mei_me snd_hwdep i2c_i801 i2c_smbus snd_soc_rt5663 mei snd_soc_rt5514 snd_soc_rt5514_spi snd_soc_max98927 rfkill snd_soc_rl6231 snd_soc_core processor_thermal_device_pci_legacy snd_compress ac97_bus snd_pcm_dmaengine snd_seq processor_thermal_device processor_thermal_rfim processor_thermal_mbox processor_thermal_rapl snd_seq_device intel_rapl_common intel_pch_thermal snd_pcm intel_xhci_usb_role_switch idma64 intel_soc_dts_iosf snd_timer snd cros_ec_i2c soundcore tpm_tis_i2c_cr50 cros_ec_lpcs int3403_thermal int340x_thermal_zone
 cros_ec chromeos_acpi cros_usbpd_notify int3400_thermal chromeos_pstore acpi_thermal_rel cros_kbd_led_backlight joydev loop zram i915 nvme drm_buddy video wmi crct10dif_pclmul crc32_pclmul crc32c_intel drm_display_helper polyval_clmulni sdhci_pci polyval_generic nvme_core cqhci cec sdhci spi_pxa2xx_platform ghash_clmulni_intel hid_multitouch sha512_ssse3 mmc_core nvme_common dw_dmac ttm pinctrl_sunrisepoint serio_raw ip6_tables ip_tables fuse [last unloaded: i2c_hid]
CPU: 2 PID: 1319 Comm: wireplumber Not tainted 6.2.15-300.fc38.x86_64 #1
Hardware name: Google Eve/Eve, BIOS Google_Eve.9584.230.0 09/06/2021
RIP: 0010:skl_init_module+0x842/0x860 [snd_soc_skl]
Code: b5 fe ff ff b9 04 00 00 00 4c 89 fe 4c 89 04 24 48 c7 c2 08 b7 16 c1 48 c7 c7 60 b7 16 c1 c6 05 73 62 02 00 01 e8 0e 5f fb f0 <0f> 0b 4c 8b 04 24 e9 84 fe ff ff e8 ae e6 e0 f1 66 66 2e 0f 1f 84
RSP: 0018:ffff9e0482017b10 EFLAGS: 00010286
RAX: 0000000000000000 RBX: ffff8d439d96ac28 RCX: 0000000000000000
RDX: 0000000000000002 RSI: 0000000000000027 RDI: 00000000ffffffff
RBP: ffff8d438733c028 R08: 0000000000000000 R09: ffff9e04820179a0
R10: 0000000000000003 R11: ffffffffb41447c8 R12: 00000000000000b8
R13: 00000000000000b8 R14: ffff8d43da783e40 R15: 0000000000000064
FS:  00007f31d534f800(0000) GS:ffff8d46eed00000(0000) knlGS:0000000000000000
CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
CR2: 00007f02b4060018 CR3: 0000000157e4e006 CR4: 00000000003706e0
DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
Call Trace:
 <TASK>
 skl_tplg_mixer_event+0x5bb/0xc50 [snd_soc_skl]
 dapm_seq_check_event+0x109/0x1e0 [snd_soc_core]
 dapm_seq_run_coalesced+0x84/0x1c0 [snd_soc_core]
 dapm_seq_run+0xb4/0x3c0 [snd_soc_core]
 dapm_power_widgets+0x6fa/0xae0 [snd_soc_core]
 snd_soc_dapm_stream_event+0xf1/0x170 [snd_soc_core]
 __soc_pcm_prepare+0x5a/0x120 [snd_soc_core]
 dpcm_fe_dai_prepare+0xac/0x1b0 [snd_soc_core]
 snd_pcm_do_prepare+0x26/0x40 [snd_pcm]
 snd_pcm_action_single+0x33/0x80 [snd_pcm]
 snd_pcm_action_nonatomic+0x95/0xa0 [snd_pcm]
 snd_pcm_ioctl+0x2a/0x40 [snd_pcm]
 __x64_sys_ioctl+0x8d/0xd0
 do_syscall_64+0x59/0x90
 ? exit_to_user_mode_prepare+0x13a/0x1f0
 ? syscall_exit_to_user_mode+0x17/0x40
 ? do_syscall_64+0x68/0x90
 ? exc_page_fault+0x78/0x180
 entry_SYSCALL_64_after_hwframe+0x72/0xdc
RIP: 0033:0x7f31d57a2edd
Code: 04 25 28 00 00 00 48 89 45 c8 31 c0 48 8d 45 10 c7 45 b0 10 00 00 00 48 89 45 b8 48 8d 45 d0 48 89 45 c0 b8 10 00 00 00 0f 05 <89> c2 3d 00 f0 ff ff 77 1a 48 8b 45 c8 64 48 2b 04 25 28 00 00 00
RSP: 002b:00007fff954a6940 EFLAGS: 00000246 ORIG_RAX: 0000000000000010
RAX: ffffffffffffffda RBX: 0000560452e4c550 RCX: 00007f31d57a2edd
RDX: 0000000000000000 RSI: 0000000000004140 RDI: 0000000000000026
RBP: 00007fff954a6990 R08: 0000000000000000 R09: 00000000000012c0
R10: 0000000000000004 R11: 0000000000000246 R12: 0000000000000026
R13: 00007fff954a6ce0 R14: 00007fff954a7090 R15: 00007fff954a6a70
 </TASK>

It seems that this is someway sound driver related. My soun works ok, but its just annoying as I get every booth the popup telling me to report a problem, the problem is that its not possible to report as the backtrace does not contain enough info i believe.

This is happening from F37 up to now on the latest F38 stuff.

Anybody else getting this king of problem ?

**Comment by jmontleon** [comment]
Yes, you cut the top line that tells you. I believe these should be reported to kernel devs so they can be fixed. There's nothing here that is Pixelbook specific. If you're tired of the messages the best bet is to report and/or disable or uninstall gnome-abrt so it doesn't bother you.

These warnings are brought on from hardening work: https://lore.kernel.org/linux-hardening/20220901065914.1417829-2-keescook@chromium.org/

```
[   10.452071] ------------[ cut here ]------------
[   10.452075] memcpy: detected field-spanning write (size 100) of single field "cpr_mconfig->gtw_cfg.config_data" at sound/soc/intel/skylake/skl-messages.c:552 (size 4)
```

**Comment by jmontleon** [comment]
It's known about already. There's a thread here; https://lore.kernel.org/lkml/af96abd5-1eaa-a74f-cfb6-7ed82fe2207c@linux.intel.com/

Would expect it will be worked out eventually, although I don't see anything merged into the kernel yet.

I would say safe to ignore. If the messages are annoying configure gnome-abrt if possible, otherwise disable or uninstall.

**Comment by saxa** [comment]
Oh I see Jason, many thanks. I think I was the one posting that one there as I see I am in cc. Sorry for the noise.
