### ISSUE TITLE
capslock

### ISSUE THREAD

**Issue by huang-jy** [jmontleon/pixelbook-fedora#66]
I noticed you have set the meta key to be capslock (https://github.com/jmontleon/pixelbook-fedora/commit/2ceae9ce376b028b312ab5a07fc3b52309e10399) -- however, I do prefer the old, out-of-the-box option of having that key as the meta key. Is there a way I can switch it back?

**Comment by jmontleon** [comment]
Let me see what I can learn makes the best sense for shipping this; perhaps it's the case I should just have the file listed as a config in the RPM so people can update it without it being overridden on package update.

**Comment by huang-jy** [comment]
Perhaps provide both configs in the package, and symlink to a default config, but offer instructions to symlink the other should that be desired?

Or provide two packages and the user decides which to install upfront (though, admittedly, that means an extra package to maintain)

**Comment by jmontleon** [comment]
OK, so you can override it and never be burdened by an RPM update again like so:

https://man7.org/linux/man-pages/man7/hwdb.7.html
```
       The hwdb files are read from the files located in the system hwdb
       directory /usr/lib/udev/hwdb.d and the local administration
       directory /etc/udev/hwdb.d. All hwdb files are collectively
       sorted and processed in lexical order, regardless of the
       directories in which they live. However, files with identical
       filenames replace each other. Files in /etc/ have the highest
       priority and take precedence over files with the same name in
       /usr/lib/. This can be used to override a system-supplied hwdb
       file with a local file if needed; a symlink in /etc/ with the
       same name as a hwdb file in /usr/lib/, pointing to /dev/null,
       disables that hwdb file entirely. hwdb files must have the
       extension .hwdb; other extensions are ignored.
```

So as a user who wants a custom config the easiest option is to just copy it to /etc/udev/hwdb.d, edit and probably run:
```
systemd-hwdb update
udevadm control --reload-rules
udevadm trigger
```

There's also the option of setting the file as `%config(noreplace)` but telling people to edit files in `/usr/lib` makes me feel like a bad person, so I'd think in that case I update the package to `/etc/udev/hwdb.d`, which is going to bounce things around again and be disruptive.

What's your feeling? The copy to etc and update as desired feels like the right path to me. If I want to change a systemd service for instance I'd do the same. If I strained my brain I'm 99.9% certain I could think of another case where this is the way to override something. But I'm open to other ideas/opinions.

I'm inclined to add an option to the ansible playbook so it can be run to add a leave left meta as meta option, so it can do all the dirty work. If I knew everything I know now before I edited the RPM I would have been inclined to do it all the opposite.

**Comment by jmontleon** [comment]
1. I think it would be either leave it the way it is and users can copy it to /etc/udev/hwdb.d to override.
2. Or edit the package to install it in /etc/udev/hwdb.d and add the `%config(noreplace)` macro so if someone edits it their changes don't get stomped on.

It should be possible in either case to make a change to the ansible playbook to provide an option for configuring it as desired by the user so it's a little easier, and to update the readme with manual instructions. I am more in favor of option 1 since it seems to be the way most things that can be overridden work.

**Comment by huang-jy** [comment]
I agree. For 90% of users, they will probably be happy with it the way it is. If they want to override, they can do the copy to /etc/udev/hwdb.d

**Comment by jmontleon** [comment]
Cool. I will work on something when time permits to make an option when running the playbook so it's a little easier.

**Comment by jmontleon** [comment]
And again apologies for the shuffle. If I looked before I leaped and learned all this before changing the package I would have just overridden it and make it an option in reverse.
