### ISSUE TITLE
Unable to add COPR: No builds

### ISSUE THREAD

**Issue by eletious** [jmontleon/pixelbook-fedora#7]
When I run `sudo dnf -y copr enable jmontleaon/pixelbook` I get an error from DNF: 
```
Error: This repository does not have any builds yet so you cannot enable it now.
```

Recently upgraded from Fedora 34, which may be related.  Does the installation have to be a fresh installation of Fedora 35?

**Comment by jmontleon** [comment]
You have an extra `a` in there :)

`sudo dnf -y copr enable jmontleon/pixelbook` should do it.

**Comment by eletious** [comment]
Hah, yeah, that did it.  Can't believe I got as worried as I did :sweat_smile: 

Thanks for the response, I think I'm good to go now!
