### ISSUE TITLE
Ansible / Copr error

### ISSUE THREAD

**Issue by EMLommers** [jmontleon/pixelbook-fedora#70]
Hi Jason,

I encountered an error during the ansible setup:
<pre>
TASK [Install pixelbook packages from COPR] ************************************
fatal: [localhost]: FAILED! => {"changed": false, "failures": [], "msg": "Depsolve Error occurred: \n Problem: conflicting requests\n  - nothing provides python3-pynput needed by pixelbook-scripts-1.0.8-1.fc38.noarch from copr:copr.fedorainfracloud.org:jmontleon:pixelbook", "rc": 1, "results": []}
</pre>
And also:
<pre>
Install package 'python3-pip' to provide command 'pip'? [N/y] y

 * Waiting in queue... 
 * Loading list of packages.... 
The following packages have to be installed:
 python3-pip-22.3.1-3.fc38.noarch	A tool for installing and managing Python3 packages
Proceed with changes? [N/y] y

 * Waiting in queue... 
 * Waiting for authentication... 
 * Waiting in queue... 
 * Downloading packages... 
 * Requesting data... 
 * Testing changes... 
 * Installing packages... 
Defaulting to user installation because normal site-packages is not writeable
Collecting pynput
  Downloading pynput-1.7.6-py2.py3-none-any.whl (89 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.2/89.2 kB 2.2 MB/s eta 0:00:00
Requirement already satisfied: six in /usr/lib/python3.11/site-packages (from pynput) (1.16.0)
Collecting evdev>=1.3
  Downloading evdev-1.6.1.tar.gz (26 kB)
  Preparing metadata (setup.py) ... done
Collecting python-xlib>=0.17
  Downloading python_xlib-0.33-py2.py3-none-any.whl (182 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 182.2/182.2 kB 5.7 MB/s eta 0:00:00
Installing collected packages: evdev, python-xlib, pynput
  DEPRECATION: evdev is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for evdev ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for evdev did not run successfully.
  │ exit code: 1
  ╰─> [39 lines of output]
      running install
      /usr/lib/python3.11/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-311
      creating build/lib.linux-x86_64-cpython-311/evdev
      copying evdev/util.py -> build/lib.linux-x86_64-cpython-311/evdev
      copying evdev/uinput.py -> build/lib.linux-x86_64-cpython-311/evdev
      copying evdev/genecodes.py -> build/lib.linux-x86_64-cpython-311/evdev
      copying evdev/ff.py -> build/lib.linux-x86_64-cpython-311/evdev
      copying evdev/evtest.py -> build/lib.linux-x86_64-cpython-311/evdev
      copying evdev/events.py -> build/lib.linux-x86_64-cpython-311/evdev
      copying evdev/eventio_async.py -> build/lib.linux-x86_64-cpython-311/evdev
      copying evdev/eventio.py -> build/lib.linux-x86_64-cpython-311/evdev
      copying evdev/ecodes.py -> build/lib.linux-x86_64-cpython-311/evdev
      copying evdev/device.py -> build/lib.linux-x86_64-cpython-311/evdev
      copying evdev/__init__.py -> build/lib.linux-x86_64-cpython-311/evdev
      running build_ext
      running build_ecodes
      The 'linux/input.h' and 'linux/input-event-codes.h' include files
      are missing. You will have to install the kernel header files in
      order to continue:
      
          yum install kernel-headers-$(uname -r)
          apt-get install linux-headers-$(uname -r)
          emerge sys-kernel/linux-headers
          pacman -S kernel-headers
      
      In case they are installed in a non-standard location, you may use
      the '--evdev-headers' option to specify one or more colon-separated
      paths. For example:
      
          python setup.py \
            build \
            build_ecodes --evdev-headers path/input.h:path/input-event-codes.h \
            build_ext --include-dirs  path/ \
            install
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> evdev

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

[emlommers@fedora pixelbook-fedora-main]$ pip install python3-pynput
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement python3-pynput (from versions: none)
ERROR: No matching distribution found for python3-pynput
[emlommers@fedora pixelbook-fedora-main]$ pip install python-pynput
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement python-pynput (from versions: none)
ERROR: No matching distribution found for python-pynput

</pre>

**Comment by jmontleon** [comment]
I can reproduce this. Copr shows it should be available (forked), but it seems it's not. I am running a rebuild of the package to hopefully sort it out. This may be the result of some cleanup / rebuilds for F39 I was doing a few weeks ago.

![image](https://github.com/jmontleon/pixelbook-fedora/assets/1850500/0c3c8eef-fee9-4c4c-ac3a-70966479e1aa)

**Comment by jmontleon** [comment]
It should be available now.
